"""questionnaire.py -- Sleep Assessment v2 (25 questions), embedded with scale anchors."""

QUESTIONS = [{'qid': 'QST_00001',
  'primary': 'VAR_032',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How long does it usually take you to fall asleep once you turn the light off?',
  'low': 'Over an hour',
  'high': 'Under 10 minutes'},
 {'qid': 'QST_00002',
  'primary': 'VAR_125',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How many times do you typically wake during the night?',
  'low': 'Five or more times',
  'high': 'Not at all'},
 {'qid': 'QST_00003',
  'primary': 'VAR_121',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'When you wake at night, how long are you usually awake before falling back asleep?',
  'low': 'Over an hour in total',
  'high': 'A minute or two'},
 {'qid': 'QST_00004',
  'primary': 'VAR_123',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'Overall, how much do difficulties with sleep interfere with your daily life?',
  'low': 'Severely',
  'high': 'Not at all'},
 {'qid': 'QST_00005',
  'primary': 'VAR_124',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How tired or fatigued do you feel during a typical day?',
  'low': 'Exhausted most of the day',
  'high': 'Consistently energetic'},
 {'qid': 'QST_00006',
  'primary': 'VAR_122',
  'secondary': ['VAR_015'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'At bedtime, how wired, alert or racing does your mind or body feel?',
  'low': 'Completely wired',
  'high': 'Calm and settled'},
 {'qid': 'QST_00007',
  'primary': 'VAR_015',
  'secondary': ['VAR_122'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'In general, how anxious or worried have you felt over the past month?',
  'low': 'Extremely anxious',
  'high': 'Not anxious at all'},
 {'qid': 'QST_00008',
  'primary': 'VAR_126',
  'secondary': ['VAR_024'],
  'reverse': True,
  'category': 'Symptom',
  'text': 'How often do you snore loudly, or has anyone told you that you do?',
  'low': 'Every night, loudly',
  'high': 'Never'},
 {'qid': 'QST_00009',
  'primary': 'VAR_024',
  'secondary': ['VAR_126'],
  'reverse': True,
  'category': 'Symptom',
  'text': 'Has anyone witnessed you gasping, choking or stopping breathing in your sleep?',
  'low': 'Often, or I have a diagnosis',
  'high': 'Never'},
 {'qid': 'QST_00010',
  'primary': 'VAR_070',
  'secondary': ['VAR_032'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How well does your natural sleep timing match the schedule your life requires?',
  'low': 'Completely mismatched',
  'high': 'Perfectly aligned'},
 {'qid': 'QST_00011',
  'primary': 'VAR_127',
  'secondary': ['VAR_125'],
  'reverse': True,
  'category': 'Symptom',
  'text': 'How often is your sleep disturbed by noise, light, a partner, pets or children?',
  'low': 'Every night',
  'high': 'Never'},
 {'qid': 'QST_00012',
  'primary': 'VAR_119',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How many hours do you usually sleep on a typical night?',
  'low': 'Under 5 or over 10 hours',
  'high': 'Between 7 and 9 hours'},
 {'qid': 'QST_00013',
  'primary': 'VAR_023',
  'secondary': ['VAR_031'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'Overall, how would you rate the quality of your sleep over the past month?',
  'low': 'Very poor',
  'high': 'Excellent'},
 {'qid': 'QST_00014',
  'primary': 'VAR_098',
  'secondary': ['VAR_070'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How consistently do you go to bed at roughly the same time each night?',
  'low': 'Varies by 2+ hours',
  'high': 'Within 30 minutes'},
 {'qid': 'QST_00015',
  'primary': 'VAR_099',
  'secondary': ['VAR_070', 'VAR_032'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How well do you avoid caffeine within six hours of bedtime?',
  'low': 'Never avoid it',
  'high': 'Always avoid it'},
 {'qid': 'QST_00016',
  'primary': 'VAR_100',
  'secondary': ['VAR_045', 'VAR_032'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How well do you avoid screens in the hour before bed?',
  'low': 'Screens right up to sleep',
  'high': 'No screens for an hour+'},
 {'qid': 'QST_00017',
  'primary': 'VAR_101',
  'secondary': ['VAR_121', 'VAR_125'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How well do you avoid alcohol within three hours of bedtime?',
  'low': 'Often drink close to bed',
  'high': 'Always avoid it'},
 {'qid': 'QST_00018',
  'primary': 'VAR_105',
  'secondary': ['VAR_127', 'VAR_125'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How quiet is your bedroom while you sleep?',
  'low': 'Frequently noisy',
  'high': 'Consistently quiet'},
 {'qid': 'QST_00019',
  'primary': 'VAR_103',
  'secondary': ['VAR_045', 'VAR_070'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How dark is your bedroom while you sleep?',
  'low': 'Noticeably lit',
  'high': 'Completely dark'},
 {'qid': 'QST_00020',
  'primary': 'VAR_104',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How comfortable is the temperature in your bedroom at night?',
  'low': 'Too hot or too cold',
  'high': 'Consistently comfortable'},
 {'qid': 'QST_00021',
  'primary': 'VAR_106',
  'secondary': ['VAR_121'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How comfortable and supportive are your mattress and pillow?',
  'low': 'Uncomfortable',
  'high': 'Very comfortable'},
 {'qid': 'QST_00022',
  'primary': 'VAR_113',
  'secondary': ['VAR_122'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'Do you have a wind-down routine in the 30 minutes before bed?',
  'low': 'None at all',
  'high': 'A consistent routine'},
 {'qid': 'QST_00023',
  'primary': 'VAR_114',
  'secondary': ['VAR_122', 'VAR_015'],
  'reverse': True,
  'category': 'Behaviour',
  'text': 'How often does your mind race or ruminate when you are trying to sleep?',
  'low': 'Every night',
  'high': 'Never'},
 {'qid': 'QST_00024',
  'primary': 'VAR_111',
  'secondary': ['VAR_070', 'VAR_032'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How well do you keep naps short and early in the afternoon?',
  'low': 'Long or late naps often',
  'high': 'Short and early, or none'},
 {'qid': 'QST_00025',
  'primary': 'VAR_109',
  'secondary': ['VAR_070'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How much bright daylight do you get within an hour of waking?',
  'low': 'Almost none',
  'high': 'Plenty, most mornings'}]
