"""questionnaire.py -- Sleep Assessment v2.2 (25 questions), embedded.

Every question lists its answer OPTIONS in the order they are shown, and each
option carries its own SCORE: 1 is the bad end, 5 the good end. The page never
shows the numbers; it shows the option labels and sends the score.

Display order and score are deliberately separate. Q12 (total sleep) shows
hours in natural order, but 7-9 hours scores 5 and "More than 9 hours" scores 3:
long sleep must not count as WEAK, because a weak VAR_119 would pull actions
that INCREASE sleep -- advice to sleep more for someone already sleeping 10 h.
Long sleep goes to the sleep-expert review instead.

'topic' is the plain-language name the page uses in "Where you have most to gain".
'low'/'high' are the labels of the lowest- and highest-scoring options (kept for
the chat prompt and older callers). Nothing is reverse-scored.

Changes from v2.1 (1 Oct 2026): Q12 bands; Q15 asks hours before bed of the last
caffeine of any kind; Q17 asks plain frequency; Q25 asks wake-time consistency to
match its variable VAR_109 (the old daylight wording had no variable; logged as a
GAP); 'labels'/'anchors' replaced by 'options' with explicit scores.
"""

SURVEY_VERSION = "2.2"

QUESTIONS = [{'qid': 'QST_00001',
  'primary': 'VAR_032',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'falling asleep',
  'text': 'How long does it usually take you to fall asleep once you turn the light off?',
  'low': 'Over an hour',
  'high': 'Under 10 minutes',
  'options': [{'label': 'Over an hour', 'score': 1},
              {'label': '30 to 60 minutes', 'score': 2},
              {'label': '20 to 30 minutes', 'score': 3},
              {'label': '10 to 20 minutes', 'score': 4},
              {'label': 'Under 10 minutes', 'score': 5}]},
 {'qid': 'QST_00002',
  'primary': 'VAR_125',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'waking during the night',
  'text': 'How many times do you typically wake during the night?',
  'low': 'Five or more times',
  'high': 'Not at all',
  'options': [{'label': 'Five or more times', 'score': 1},
              {'label': 'Three or four times', 'score': 2},
              {'label': 'Twice', 'score': 3},
              {'label': 'Once', 'score': 4},
              {'label': 'Not at all', 'score': 5}]},
 {'qid': 'QST_00003',
  'primary': 'VAR_121',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'getting back to sleep',
  'text': 'When you wake at night, how long are you usually awake before falling back asleep?',
  'low': 'Over an hour in total',
  'high': 'A minute or two',
  'options': [{'label': 'Over an hour in total', 'score': 1},
              {'label': '30 to 60 minutes', 'score': 2},
              {'label': '10 to 30 minutes', 'score': 3},
              {'label': 'A few minutes', 'score': 4},
              {'label': 'A minute or two', 'score': 5}]},
 {'qid': 'QST_00004',
  'primary': 'VAR_123',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'how sleep affects your day',
  'text': 'Overall, how much do difficulties with sleep interfere with your daily life?',
  'low': 'Severely',
  'high': 'Not at all',
  'options': [{'label': 'Severely', 'score': 1},
              {'label': 'A lot', 'score': 2},
              {'label': 'Somewhat', 'score': 3},
              {'label': 'A little', 'score': 4},
              {'label': 'Not at all', 'score': 5}]},
 {'qid': 'QST_00005',
  'primary': 'VAR_124',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'daytime energy',
  'text': 'How tired or fatigued do you feel during a typical day?',
  'low': 'Exhausted most of the day',
  'high': 'Consistently energetic',
  'options': [{'label': 'Exhausted most of the day', 'score': 1},
              {'label': 'Often tired', 'score': 2},
              {'label': 'Sometimes tired', 'score': 3},
              {'label': 'Mostly alert', 'score': 4},
              {'label': 'Consistently energetic', 'score': 5}]},
 {'qid': 'QST_00006',
  'primary': 'VAR_122',
  'secondary': ['VAR_015'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'feeling calm at bedtime',
  'text': 'At bedtime, how wired, alert or racing does your mind or body feel?',
  'low': 'Completely wired',
  'high': 'Calm and settled',
  'options': [{'label': 'Completely wired', 'score': 1},
              {'label': 'Quite restless', 'score': 2},
              {'label': 'Somewhat alert', 'score': 3},
              {'label': 'Mostly calm', 'score': 4},
              {'label': 'Calm and settled', 'score': 5}]},
 {'qid': 'QST_00007',
  'primary': 'VAR_015',
  'secondary': ['VAR_122'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'worry and anxiety',
  'text': 'In general, how anxious or worried have you felt over the past month?',
  'low': 'Extremely anxious',
  'high': 'Not anxious at all',
  'options': [{'label': 'Extremely anxious', 'score': 1},
              {'label': 'Very anxious', 'score': 2},
              {'label': 'Somewhat anxious', 'score': 3},
              {'label': 'Slightly anxious', 'score': 4},
              {'label': 'Not anxious at all', 'score': 5}]},
 {'qid': 'QST_00008',
  'primary': 'VAR_126',
  'secondary': ['VAR_024'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'snoring',
  'text': 'How often do you snore loudly, or has anyone told you that you do?',
  'low': 'Every night, loudly',
  'high': 'Never',
  'options': [{'label': 'Every night, loudly', 'score': 1},
              {'label': 'Most nights', 'score': 2},
              {'label': 'Some nights', 'score': 3},
              {'label': 'Rarely', 'score': 4},
              {'label': 'Never', 'score': 5}]},
 {'qid': 'QST_00009',
  'primary': 'VAR_024',
  'secondary': ['VAR_126'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'breathing during sleep',
  'text': 'Has anyone witnessed you gasping, choking or stopping breathing in your sleep?',
  'low': 'Often, or I have a diagnosis',
  'high': 'Never',
  'options': [{'label': 'Often, or I have a diagnosis', 'score': 1},
              {'label': 'Several times', 'score': 2},
              {'label': 'Once or twice', 'score': 3},
              {'label': 'Very rarely', 'score': 4},
              {'label': 'Never', 'score': 5}]},
 {'qid': 'QST_00010',
  'primary': 'VAR_070',
  'secondary': ['VAR_032'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'the timing of your sleep',
  'text': 'How well does your natural sleep timing match the schedule your life requires?',
  'low': 'Completely mismatched',
  'high': 'Perfectly aligned',
  'options': [{'label': 'Completely mismatched', 'score': 1},
              {'label': 'Mostly mismatched', 'score': 2},
              {'label': 'Partly aligned', 'score': 3},
              {'label': 'Mostly aligned', 'score': 4},
              {'label': 'Perfectly aligned', 'score': 5}]},
 {'qid': 'QST_00011',
  'primary': 'VAR_127',
  'secondary': ['VAR_125'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'disturbances at night',
  'text': 'How often is your sleep disturbed by noise, light, a partner, pets or children?',
  'low': 'Every night',
  'high': 'Never',
  'options': [{'label': 'Every night', 'score': 1},
              {'label': 'Most nights', 'score': 2},
              {'label': 'Some nights', 'score': 3},
              {'label': 'Rarely', 'score': 4},
              {'label': 'Never', 'score': 5}]},
 {'qid': 'QST_00012',
  'primary': 'VAR_119',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'how long you sleep',
  'text': 'How many hours do you usually sleep on a typical night?',
  'low': 'Under 5 hours',
  'high': '7 to 9 hours',
  'options': [{'label': 'Under 5 hours', 'score': 1},
              {'label': '5 to 6 hours', 'score': 2},
              {'label': '6 to 7 hours', 'score': 3},
              {'label': '7 to 9 hours', 'score': 5},
              {'label': 'More than 9 hours', 'score': 3}]},
 {'qid': 'QST_00013',
  'primary': 'VAR_023',
  'secondary': ['VAR_031'],
  'reverse': False,
  'category': 'Symptom',
  'topic': 'overall sleep quality',
  'text': 'Overall, how would you rate the quality of your sleep over the past month?',
  'low': 'Very poor',
  'high': 'Excellent',
  'options': [{'label': 'Very poor', 'score': 1},
              {'label': 'Poor', 'score': 2},
              {'label': 'Fair', 'score': 3},
              {'label': 'Good', 'score': 4},
              {'label': 'Excellent', 'score': 5}]},
 {'qid': 'QST_00014',
  'primary': 'VAR_098',
  'secondary': ['VAR_070'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'a regular bedtime',
  'text': 'How consistently do you go to bed at roughly the same time each night?',
  'low': 'Varies by 2 hours or more',
  'high': 'Within 30 minutes',
  'options': [{'label': 'Varies by 2 hours or more', 'score': 1},
              {'label': 'Within 1 to 2 hours', 'score': 2},
              {'label': 'Within an hour', 'score': 3},
              {'label': 'Within 45 minutes', 'score': 4},
              {'label': 'Within 30 minutes', 'score': 5}]},
 {'qid': 'QST_00015',
  'primary': 'VAR_099',
  'secondary': ['VAR_070', 'VAR_032'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'caffeine timing',
  'text': 'How many hours before bed do you have your last caffeine (coffee, tea, cola, energy drinks)?',
  'low': 'Less than 2 hours',
  'high': 'More than 8 hours, or no caffeine',
  'options': [{'label': 'Less than 2 hours', 'score': 1},
              {'label': '2 to 4 hours', 'score': 2},
              {'label': '4 to 6 hours', 'score': 3},
              {'label': '6 to 8 hours', 'score': 4},
              {'label': 'More than 8 hours, or no caffeine', 'score': 5}]},
 {'qid': 'QST_00016',
  'primary': 'VAR_100',
  'secondary': ['VAR_045', 'VAR_032'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'screens before bed',
  'text': 'How well do you avoid screens in the hour before bed?',
  'low': 'Screens right up to sleep',
  'high': 'No screens for an hour or more',
  'options': [{'label': 'Screens right up to sleep', 'score': 1},
              {'label': 'Stop 10 to 15 minutes before', 'score': 2},
              {'label': 'Stop 30 minutes before', 'score': 3},
              {'label': 'Stop 45 minutes before', 'score': 4},
              {'label': 'No screens for an hour or more', 'score': 5}]},
 {'qid': 'QST_00017',
  'primary': 'VAR_101',
  'secondary': ['VAR_121', 'VAR_125'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'alcohol before bed',
  'text': 'How often do you drink alcohol within three hours of going to bed?',
  'low': 'Most nights',
  'high': 'Never',
  'options': [{'label': 'Most nights', 'score': 1},
              {'label': 'A few nights a week', 'score': 2},
              {'label': 'About once a week', 'score': 3},
              {'label': 'Less than once a week', 'score': 4},
              {'label': 'Never', 'score': 5}]},
 {'qid': 'QST_00018',
  'primary': 'VAR_105',
  'secondary': ['VAR_127', 'VAR_125'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'a quiet bedroom',
  'text': 'How quiet is your bedroom while you sleep?',
  'low': 'Frequently noisy',
  'high': 'Consistently quiet',
  'options': [{'label': 'Frequently noisy', 'score': 1},
              {'label': 'Often noisy', 'score': 2},
              {'label': 'Sometimes noisy', 'score': 3},
              {'label': 'Mostly quiet', 'score': 4},
              {'label': 'Consistently quiet', 'score': 5}]},
 {'qid': 'QST_00019',
  'primary': 'VAR_103',
  'secondary': ['VAR_045', 'VAR_070'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'a dark bedroom',
  'text': 'How dark is your bedroom while you sleep?',
  'low': 'Noticeably lit',
  'high': 'Completely dark',
  'options': [{'label': 'Noticeably lit', 'score': 1},
              {'label': 'Fairly lit', 'score': 2},
              {'label': 'Dim', 'score': 3},
              {'label': 'Mostly dark', 'score': 4},
              {'label': 'Completely dark', 'score': 5}]},
 {'qid': 'QST_00020',
  'primary': 'VAR_104',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'bedroom temperature',
  'text': 'How comfortable is the temperature in your bedroom at night?',
  'low': 'Too hot or too cold',
  'high': 'Consistently comfortable',
  'options': [{'label': 'Too hot or too cold', 'score': 1},
              {'label': 'Often uncomfortable', 'score': 2},
              {'label': 'Sometimes uncomfortable', 'score': 3},
              {'label': 'Mostly comfortable', 'score': 4},
              {'label': 'Consistently comfortable', 'score': 5}]},
 {'qid': 'QST_00021',
  'primary': 'VAR_106',
  'secondary': ['VAR_121'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'your mattress and pillow',
  'text': 'How comfortable and supportive are your mattress and pillow?',
  'low': 'Uncomfortable',
  'high': 'Very comfortable',
  'options': [{'label': 'Uncomfortable', 'score': 1},
              {'label': 'Somewhat uncomfortable', 'score': 2},
              {'label': 'Acceptable', 'score': 3},
              {'label': 'Comfortable', 'score': 4},
              {'label': 'Very comfortable', 'score': 5}]},
 {'qid': 'QST_00022',
  'primary': 'VAR_113',
  'secondary': ['VAR_122'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'a wind-down routine',
  'text': 'Do you have a wind-down routine in the 30 minutes before bed?',
  'low': 'None at all',
  'high': 'A consistent routine',
  'options': [{'label': 'None at all', 'score': 1},
              {'label': 'Rarely', 'score': 2},
              {'label': 'Some nights', 'score': 3},
              {'label': 'Most nights', 'score': 4},
              {'label': 'A consistent routine', 'score': 5}]},
 {'qid': 'QST_00023',
  'primary': 'VAR_114',
  'secondary': ['VAR_122', 'VAR_015'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'a racing mind at night',
  'text': 'How often does your mind race or ruminate when you are trying to sleep?',
  'low': 'Every night',
  'high': 'Never',
  'options': [{'label': 'Every night', 'score': 1},
              {'label': 'Most nights', 'score': 2},
              {'label': 'Some nights', 'score': 3},
              {'label': 'Rarely', 'score': 4},
              {'label': 'Never', 'score': 5}]},
 {'qid': 'QST_00024',
  'primary': 'VAR_111',
  'secondary': ['VAR_070', 'VAR_032'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'naps',
  'text': 'How well do you keep naps short and early in the afternoon?',
  'low': 'Long or late naps, often',
  'high': 'Short and early, or none',
  'options': [{'label': 'Long or late naps, often', 'score': 1},
              {'label': 'Sometimes long or late', 'score': 2},
              {'label': 'Occasionally', 'score': 3},
              {'label': 'Mostly short and early', 'score': 4},
              {'label': 'Short and early, or none', 'score': 5}]},
 {'qid': 'QST_00025',
  'primary': 'VAR_109',
  'secondary': ['VAR_070'],
  'reverse': False,
  'category': 'Behaviour',
  'topic': 'a regular wake time',
  'text': 'How consistent is the time you wake up, including weekends?',
  'low': 'Varies by 2 hours or more',
  'high': 'Within 30 minutes',
  'options': [{'label': 'Varies by 2 hours or more', 'score': 1},
              {'label': 'Within 1 to 2 hours', 'score': 2},
              {'label': 'Within an hour', 'score': 3},
              {'label': 'Within 45 minutes', 'score': 4},
              {'label': 'Within 30 minutes', 'score': 5}]}]
