"""questionnaire.py -- Sleep Assessment v2.1 (25 questions), embedded.

Convention: for EVERY question, answer 1 is the bad end and 5 the good end,
so no question is reverse-scored. Each answer has its own label.
"""

QUESTIONS = [{'qid': 'QST_00001',
  'primary': 'VAR_032',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How long does it usually take you to fall asleep once you turn the light off?',
  'low': 'Over an hour',
  'high': 'Under 10 minutes',
  'anchors': ['Over an hour', '30 to 60 minutes', '20 to 30 minutes', '10 to 20 minutes', 'Under 10 minutes'],
  'labels': ['Over an hour', '30 to 60 minutes', '20 to 30 minutes', '10 to 20 minutes', 'Under 10 minutes']},
 {'qid': 'QST_00002',
  'primary': 'VAR_125',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How many times do you typically wake during the night?',
  'low': 'Five or more times',
  'high': 'Not at all',
  'anchors': ['Five or more times', '3 or 4 times', 'Twice', 'Once', 'Not at all'],
  'labels': ['Five or more times', 'Three or four times', 'Twice', 'Once', 'Not at all']},
 {'qid': 'QST_00003',
  'primary': 'VAR_121',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'When you wake at night, how long are you usually awake before falling back asleep?',
  'low': 'Over an hour in total',
  'high': 'A minute or two',
  'anchors': ['Over an hour in total',
              '30 to 60 minutes',
              '10 to 30 minutes',
              '3 to 10 minutes',
              'A minute or two'],
  'labels': ['Over an hour in total',
             '30 to 60 minutes',
             '10 to 30 minutes',
             'A few minutes',
             'A minute or two']},
 {'qid': 'QST_00004',
  'primary': 'VAR_123',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'Overall, how much do difficulties with sleep interfere with your daily life?',
  'low': 'Severely',
  'high': 'Not at all',
  'anchors': ['Severely', 'A lot', 'Somewhat', 'A little', 'Not at all'],
  'labels': ['Severely', 'A lot', 'Somewhat', 'A little', 'Not at all']},
 {'qid': 'QST_00005',
  'primary': 'VAR_124',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How tired or fatigued do you feel during a typical day?',
  'low': 'Exhausted most of the day',
  'high': 'Consistently energetic',
  'anchors': ['Exhausted most of the day',
              'Tired much of the day',
              'Tired at times',
              'Mostly energetic',
              'Consistently energetic'],
  'labels': ['Exhausted most of the day',
             'Often tired',
             'Sometimes tired',
             'Mostly alert',
             'Consistently energetic']},
 {'qid': 'QST_00006',
  'primary': 'VAR_122',
  'secondary': ['VAR_015'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'At bedtime, how wired, alert or racing does your mind or body feel?',
  'low': 'Completely wired',
  'high': 'Calm and settled',
  'anchors': ['Completely wired', 'Quite restless', 'Somewhat alert', 'Mostly calm', 'Calm and settled'],
  'labels': ['Completely wired', 'Quite restless', 'Somewhat alert', 'Mostly calm', 'Calm and settled']},
 {'qid': 'QST_00007',
  'primary': 'VAR_015',
  'secondary': ['VAR_122'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'In general, how anxious or worried have you felt over the past month?',
  'low': 'Extremely anxious',
  'high': 'Not anxious at all',
  'anchors': ['Extremely anxious',
              'Very anxious',
              'Moderately anxious',
              'Slightly anxious',
              'Not anxious at all'],
  'labels': ['Extremely anxious',
             'Very anxious',
             'Somewhat anxious',
             'Slightly anxious',
             'Not anxious at all']},
 {'qid': 'QST_00008',
  'primary': 'VAR_126',
  'secondary': ['VAR_024'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How often do you snore loudly, or has anyone told you that you do?',
  'low': 'Every night, loudly',
  'high': 'Never',
  'anchors': ['Every night, loudly', 'Most nights', 'Some nights', 'Rarely', 'Never'],
  'labels': ['Every night, loudly', 'Most nights', 'Some nights', 'Rarely', 'Never']},
 {'qid': 'QST_00009',
  'primary': 'VAR_024',
  'secondary': ['VAR_126'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'Has anyone witnessed you gasping, choking or stopping breathing in your sleep?',
  'low': 'Often, or I have a diagnosis',
  'high': 'Never',
  'anchors': ['Often, or I have a diagnosis',
              'Several times',
              'Once or twice',
              'Not that I know of',
              'Never'],
  'labels': ['Often, or I have a diagnosis', 'Several times', 'Once or twice', 'Very rarely', 'Never']},
 {'qid': 'QST_00010',
  'primary': 'VAR_070',
  'secondary': ['VAR_032'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How well does your natural sleep timing match the schedule your life requires?',
  'low': 'Completely mismatched',
  'high': 'Perfectly aligned',
  'anchors': ['Completely mismatched',
              'Mostly mismatched',
              'Partly aligned',
              'Mostly aligned',
              'Perfectly aligned'],
  'labels': ['Completely mismatched',
             'Mostly mismatched',
             'Partly aligned',
             'Mostly aligned',
             'Perfectly aligned']},
 {'qid': 'QST_00011',
  'primary': 'VAR_127',
  'secondary': ['VAR_125'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How often is your sleep disturbed by noise, light, a partner, pets or children?',
  'low': 'Every night',
  'high': 'Never',
  'anchors': ['Every night', 'Most nights', 'Some nights', 'Rarely', 'Never'],
  'labels': ['Every night', 'Most nights', 'Some nights', 'Rarely', 'Never']},
 {'qid': 'QST_00012',
  'primary': 'VAR_119',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'How many hours do you usually sleep on a typical night?',
  'low': 'Under 5 hours, or over 10',
  'high': 'Between 7 and 9 hours',
  'anchors': ['Under 5, or over 10 hours',
              '5 to 6 hours',
              '6 to 6½ hours',
              '6½ to 7, or 9 to 10 hours',
              'Between 7 and 9 hours'],
  'labels': ['Under 5 hours, or over 10',
             '5 to 6 hours',
             '6 to 6½ hours',
             '6½ to 7 hours',
             'Between 7 and 9 hours']},
 {'qid': 'QST_00013',
  'primary': 'VAR_023',
  'secondary': ['VAR_031'],
  'reverse': False,
  'category': 'Symptom',
  'text': 'Overall, how would you rate the quality of your sleep over the past month?',
  'low': 'Very poor',
  'high': 'Excellent',
  'anchors': ['Very poor', 'Poor', 'Fair', 'Good', 'Excellent'],
  'labels': ['Very poor', 'Poor', 'Fair', 'Good', 'Excellent']},
 {'qid': 'QST_00014',
  'primary': 'VAR_098',
  'secondary': ['VAR_070'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How consistently do you go to bed at roughly the same time each night?',
  'low': 'Varies by 2 hours or more',
  'high': 'Within 30 minutes',
  'anchors': ['Varies by 2+ hours',
              'Varies by 1 to 2 hours',
              'Varies by about an hour',
              'Within 45 minutes',
              'Within 30 minutes'],
  'labels': ['Varies by 2 hours or more',
             'Within 1 to 2 hours',
             'Within an hour',
             'Within 45 minutes',
             'Within 30 minutes']},
 {'qid': 'QST_00015',
  'primary': 'VAR_099',
  'secondary': ['VAR_070', 'VAR_032'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How well do you avoid caffeine within six hours of bedtime?',
  'low': 'Never avoid it',
  'high': 'Always avoid it',
  'anchors': ['Never avoid it', 'Rarely', 'Sometimes', 'Usually', 'Always avoid it'],
  'labels': ['Never avoid it', 'Rarely', 'Sometimes', 'Usually', 'Always avoid it']},
 {'qid': 'QST_00016',
  'primary': 'VAR_100',
  'secondary': ['VAR_045', 'VAR_032'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How well do you avoid screens in the hour before bed?',
  'low': 'Screens right up to sleep',
  'high': 'No screens for an hour or more',
  'anchors': ['Screens right up to sleep',
              'Off about 15 minutes before',
              'Off about 30 minutes before',
              'Off about 45 minutes before',
              'No screens for an hour or more'],
  'labels': ['Screens right up to sleep',
             'Stop 10 to 15 minutes before',
             'Stop 30 minutes before',
             'Stop 45 minutes before',
             'No screens for an hour or more']},
 {'qid': 'QST_00017',
  'primary': 'VAR_101',
  'secondary': ['VAR_121', 'VAR_125'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How well do you avoid alcohol within three hours of bedtime?',
  'low': 'Often drink close to bed',
  'high': 'Always avoid it',
  'anchors': ['Often drink close to bed', 'Sometimes', 'Occasionally', 'Rarely', 'Always avoid it'],
  'labels': ['Often drink close to bed', 'Sometimes', 'Occasionally', 'Rarely', 'Always avoid it']},
 {'qid': 'QST_00018',
  'primary': 'VAR_105',
  'secondary': ['VAR_127', 'VAR_125'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How quiet is your bedroom while you sleep?',
  'low': 'Frequently noisy',
  'high': 'Consistently quiet',
  'anchors': ['Frequently noisy', 'Often noisy', 'Sometimes noisy', 'Mostly quiet', 'Consistently quiet'],
  'labels': ['Frequently noisy', 'Often noisy', 'Sometimes noisy', 'Mostly quiet', 'Consistently quiet']},
 {'qid': 'QST_00019',
  'primary': 'VAR_103',
  'secondary': ['VAR_045', 'VAR_070'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How dark is your bedroom while you sleep?',
  'low': 'Noticeably lit',
  'high': 'Completely dark',
  'anchors': ['Noticeably lit', 'Some light', 'Dim', 'Nearly dark', 'Completely dark'],
  'labels': ['Noticeably lit', 'Fairly lit', 'Dim', 'Mostly dark', 'Completely dark']},
 {'qid': 'QST_00020',
  'primary': 'VAR_104',
  'secondary': ['VAR_023'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How comfortable is the temperature in your bedroom at night?',
  'low': 'Too hot or too cold',
  'high': 'Consistently comfortable',
  'anchors': ['Too hot or too cold',
              'Often uncomfortable',
              'Sometimes uncomfortable',
              'Mostly comfortable',
              'Consistently comfortable'],
  'labels': ['Too hot or too cold',
             'Often uncomfortable',
             'Sometimes uncomfortable',
             'Mostly comfortable',
             'Consistently comfortable']},
 {'qid': 'QST_00021',
  'primary': 'VAR_106',
  'secondary': ['VAR_121'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How comfortable and supportive are your mattress and pillow?',
  'low': 'Uncomfortable',
  'high': 'Very comfortable',
  'anchors': ['Uncomfortable', 'Somewhat uncomfortable', 'Acceptable', 'Comfortable', 'Very comfortable'],
  'labels': ['Uncomfortable', 'Somewhat uncomfortable', 'Acceptable', 'Comfortable', 'Very comfortable']},
 {'qid': 'QST_00022',
  'primary': 'VAR_113',
  'secondary': ['VAR_122'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'Do you have a wind-down routine in the 30 minutes before bed?',
  'low': 'None at all',
  'high': 'A consistent routine',
  'anchors': ['None at all', 'Rarely', 'Some nights', 'Most nights', 'A consistent routine'],
  'labels': ['None at all', 'Rarely', 'Some nights', 'Most nights', 'A consistent routine']},
 {'qid': 'QST_00023',
  'primary': 'VAR_114',
  'secondary': ['VAR_122', 'VAR_015'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How often does your mind race or ruminate when you are trying to sleep?',
  'low': 'Every night',
  'high': 'Never',
  'anchors': ['Every night', 'Most nights', 'Some nights', 'Rarely', 'Never'],
  'labels': ['Every night', 'Most nights', 'Some nights', 'Rarely', 'Never']},
 {'qid': 'QST_00024',
  'primary': 'VAR_111',
  'secondary': ['VAR_070', 'VAR_032'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How well do you keep naps short and early in the afternoon?',
  'low': 'Long or late naps, often',
  'high': 'Short and early, or none',
  'anchors': ['Long or late naps often',
              'Long or late naps sometimes',
              'Occasionally',
              'Mostly short and early',
              'Short and early, or none'],
  'labels': ['Long or late naps, often',
             'Sometimes long or late',
             'Occasionally',
             'Mostly short and early',
             'Short and early, or none']},
 {'qid': 'QST_00025',
  'primary': 'VAR_109',
  'secondary': ['VAR_070'],
  'reverse': False,
  'category': 'Behaviour',
  'text': 'How much bright daylight do you get within an hour of waking?',
  'low': 'Almost none',
  'high': 'Plenty, most mornings',
  'anchors': ['Almost none', 'A little', 'Some', 'Quite a lot', 'Plenty, most mornings'],
  'labels': ['Almost none', 'A little', 'Some', 'A good amount', 'Plenty, most mornings']}]
